name: C++ Test Workflow

on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up C++ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake libgtest-dev libgmock-dev

        - name: Install GoogleTest and GoogleMock
        run: |
          # Clone Google Test and Google Mock
          git clone --branch release-1.11.0 https://github.com/google/googletest.git
          cd googletest
          mkdir build
          cd build
          cmake ..
          sudo make install
          cd ../..

      - name: Build with CMake
        run: |
          rm -rf build/
          mkdir build
          cd build
          cmake ..
          make
          
      - name: Test
        run: |
          cd build
          ./test