name: C++ Test Workflow

on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up C++ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake libgtest-dev

      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake .. 
          make  
          
      - name: Test
        run: |
          cd build
          ./test