name: C++ Test Workflow

on: [push]

jobs:

  Clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove old files
        run: |
          rm -rf build

  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up C++ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake libgtest-dev libgmock-dev

      - name: Install GoogleTest and GoogleMock
        run: |
          # Clone Google Test and Google Mock
          git submodule add https://github.com/google/googletest.git external/googletest

      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake ..
          make
          
      - name: Test
        run: |
          cd build
          ./test